#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = google.targets.arm.Bionic{1,0,4.4,3
#
ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/release/shmbuf/package/package_ti.sdo.fc.ires.shmbuf.obnc.dep
endif

package/lib/lib/release/shmbuf/package/package_ti.sdo.fc.ires.shmbuf.obnc: | .interfaces
package/lib/lib/release/shmbuf/package/package_ti.sdo.fc.ires.shmbuf.obnc: package/package_ti.sdo.fc.ires.shmbuf.c lib/release/shmbuf.abnc.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clbnc $< ...
	/db/rtree/install/trees/products/xdcprod/xdcprod-p43/product/Linux/xdctools_3_23_01_43/packages/google/targets/runh -h sanbud01.sanb.design.ti.com $(google.targets.arm.Bionic.rootDir)/bin/arm-eabi-gcc -c  -x c  -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_4_3 -O2 -ffunction-sections -fdata-sections -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/arch-arm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libstdc++/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/common -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/arch-arm -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include/arch/arm  $(XDCINCS)  -o $@ $<
	$(MKDEP) -o $@.dep -p package/lib/lib/release/shmbuf/package/ -s obnc $< -C -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_4_3 -O2 -ffunction-sections -fdata-sections -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/arch-arm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libstdc++/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/common -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/arch-arm -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include/arch/arm  $(XDCINCS) 
	ls `dirname $@` > /dev/null
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/release/shmbuf/package/package_ti.sdo.fc.ires.shmbuf.obnc: export LD_LIBRARY_PATH=

package/lib/lib/release/shmbuf/package/package_ti.sdo.fc.ires.shmbuf.sbnc: | .interfaces
package/lib/lib/release/shmbuf/package/package_ti.sdo.fc.ires.shmbuf.sbnc: package/package_ti.sdo.fc.ires.shmbuf.c lib/release/shmbuf.abnc.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clbnc -S $< ...
	/db/rtree/install/trees/products/xdcprod/xdcprod-p43/product/Linux/xdctools_3_23_01_43/packages/google/targets/runh -h sanbud01.sanb.design.ti.com $(google.targets.arm.Bionic.rootDir)/bin/arm-eabi-gcc -c  -x c -S -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_4_3 -O2 -ffunction-sections -fdata-sections  $(XDCINCS)  -o $@ $<
	$(MKDEP) -o $@.dep -p package/lib/lib/release/shmbuf/package/ -s obnc $< -C -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_4_3 -O2 -ffunction-sections -fdata-sections  $(XDCINCS) 
	ls `dirname $@` > /dev/null
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/release/shmbuf/package/package_ti.sdo.fc.ires.shmbuf.sbnc: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/release/shmbuf/shmbuf.obnc.dep
endif

package/lib/lib/release/shmbuf/shmbuf.obnc: | .interfaces
package/lib/lib/release/shmbuf/shmbuf.obnc: shmbuf.c lib/release/shmbuf.abnc.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clbnc $< ...
	/db/rtree/install/trees/products/xdcprod/xdcprod-p43/product/Linux/xdctools_3_23_01_43/packages/google/targets/runh -h sanbud01.sanb.design.ti.com $(google.targets.arm.Bionic.rootDir)/bin/arm-eabi-gcc -c  -x c  -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_4_3 -O2 -ffunction-sections -fdata-sections -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/arch-arm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libstdc++/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/common -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/arch-arm -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include/arch/arm  $(XDCINCS)  -o $@ $<
	$(MKDEP) -o $@.dep -p package/lib/lib/release/shmbuf/ -s obnc $< -C -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_4_3 -O2 -ffunction-sections -fdata-sections -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/arch-arm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libstdc++/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/common -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/arch-arm -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include/arch/arm  $(XDCINCS) 
	ls `dirname $@` > /dev/null
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/release/shmbuf/shmbuf.obnc: export LD_LIBRARY_PATH=

package/lib/lib/release/shmbuf/shmbuf.sbnc: | .interfaces
package/lib/lib/release/shmbuf/shmbuf.sbnc: shmbuf.c lib/release/shmbuf.abnc.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clbnc -S $< ...
	/db/rtree/install/trees/products/xdcprod/xdcprod-p43/product/Linux/xdctools_3_23_01_43/packages/google/targets/runh -h sanbud01.sanb.design.ti.com $(google.targets.arm.Bionic.rootDir)/bin/arm-eabi-gcc -c  -x c -S -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_4_3 -O2 -ffunction-sections -fdata-sections  $(XDCINCS)  -o $@ $<
	$(MKDEP) -o $@.dep -p package/lib/lib/release/shmbuf/ -s obnc $< -C -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_4_3 -O2 -ffunction-sections -fdata-sections  $(XDCINCS) 
	ls `dirname $@` > /dev/null
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/release/shmbuf/shmbuf.sbnc: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/release/shmbuf/shmbuf_params.obnc.dep
endif

package/lib/lib/release/shmbuf/shmbuf_params.obnc: | .interfaces
package/lib/lib/release/shmbuf/shmbuf_params.obnc: shmbuf_params.c lib/release/shmbuf.abnc.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clbnc $< ...
	/db/rtree/install/trees/products/xdcprod/xdcprod-p43/product/Linux/xdctools_3_23_01_43/packages/google/targets/runh -h sanbud01.sanb.design.ti.com $(google.targets.arm.Bionic.rootDir)/bin/arm-eabi-gcc -c  -x c  -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_4_3 -O2 -ffunction-sections -fdata-sections -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/arch-arm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libstdc++/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/common -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/arch-arm -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include/arch/arm  $(XDCINCS)  -o $@ $<
	$(MKDEP) -o $@.dep -p package/lib/lib/release/shmbuf/ -s obnc $< -C -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_4_3 -O2 -ffunction-sections -fdata-sections -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/arch-arm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libstdc++/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/common -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/arch-arm -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include/arch/arm  $(XDCINCS) 
	ls `dirname $@` > /dev/null
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/release/shmbuf/shmbuf_params.obnc: export LD_LIBRARY_PATH=

package/lib/lib/release/shmbuf/shmbuf_params.sbnc: | .interfaces
package/lib/lib/release/shmbuf/shmbuf_params.sbnc: shmbuf_params.c lib/release/shmbuf.abnc.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clbnc -S $< ...
	/db/rtree/install/trees/products/xdcprod/xdcprod-p43/product/Linux/xdctools_3_23_01_43/packages/google/targets/runh -h sanbud01.sanb.design.ti.com $(google.targets.arm.Bionic.rootDir)/bin/arm-eabi-gcc -c  -x c -S -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_4_3 -O2 -ffunction-sections -fdata-sections  $(XDCINCS)  -o $@ $<
	$(MKDEP) -o $@.dep -p package/lib/lib/release/shmbuf/ -s obnc $< -C -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_4_3 -O2 -ffunction-sections -fdata-sections  $(XDCINCS) 
	ls `dirname $@` > /dev/null
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/release/shmbuf/shmbuf_params.sbnc: export LD_LIBRARY_PATH=

clean,bnc ::
	-$(RM) package/lib/lib/release/shmbuf/package/package_ti.sdo.fc.ires.shmbuf.obnc
	-$(RM) package/lib/lib/release/shmbuf/shmbuf.obnc
	-$(RM) package/lib/lib/release/shmbuf/shmbuf_params.obnc
	-$(RM) package/lib/lib/release/shmbuf/package/package_ti.sdo.fc.ires.shmbuf.sbnc
	-$(RM) package/lib/lib/release/shmbuf/shmbuf.sbnc
	-$(RM) package/lib/lib/release/shmbuf/shmbuf_params.sbnc

lib/release/shmbuf.abnc: package/lib/lib/release/shmbuf/package/package_ti.sdo.fc.ires.shmbuf.obnc package/lib/lib/release/shmbuf/shmbuf.obnc package/lib/lib/release/shmbuf/shmbuf_params.obnc lib/release/shmbuf.abnc.mak

clean::
	-$(RM) lib/release/shmbuf.abnc.mak
