#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = ti/syslink/samples/rtos/procMgr
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/include/utils.tci:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/include/utils.tci
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/xdc.tci:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/xdc.tci
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/template.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/template.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/om2.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/om2.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/xmlgen.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/xmlgen.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/xmlgen2.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/xmlgen2.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/IPackage.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/IPackage.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/package.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/package.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/services/global/Clock.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/services/global/Clock.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/services/global/Trace.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/services/global/Trace.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/bld.js:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/bld.js
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/BuildEnvironment.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/PackageContents.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/PackageContents.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/_gen.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/_gen.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Library.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Library.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Executable.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Executable.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Repository.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Repository.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Configuration.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Configuration.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Script.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Script.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Manifest.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Manifest.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Utils.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Utils.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/ITarget.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/ITarget.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/ITarget2.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/ITarget2.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/ITargetFilter.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/ITargetFilter.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/package.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/package.xs
/home/sksung/work/udx/ch2/ti_tools/syslink_2_10_06_28/packages/_config.bld:
package.mak: /home/sksung/work/udx/ch2/ti_tools/syslink_2_10_06_28/packages/_config.bld
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/ITarget.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/ITarget.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/C28_large.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/C28_large.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/C28_float.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/C28_float.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/package.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/package.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/elf/ITarget.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/elf/ITarget.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/elf/TMS470.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/elf/TMS470.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/elf/package.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/elf/package.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/arm/IArm.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/arm/IArm.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/arm/package.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/arm/package.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/arm/elf/IArm.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/arm/elf/IArm.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/arm/elf/package.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/arm/elf/package.xs
package.mak: package.bld
/home/sksung/work/udx/ch2/ti_tools/syslink_2_10_06_28/packages/ti/syslink/buildutils/rtos/buildScripts/common.bld:
package.mak: /home/sksung/work/udx/ch2/ti_tools/syslink_2_10_06_28/packages/ti/syslink/buildutils/rtos/buildScripts/common.bld
endif

ti.targets.elf.C674.rootDir ?= /home/sksung/work/udx/ch2/packages/../ti_tools/cgt6x_7_3_5
ti.targets.elf.packageBase ?= /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/elf/
ti.targets.arm.elf.M3.rootDir ?= /home/sksung/work/udx/ch2/packages/../ti_tools/cgt470_4_9_5
ti.targets.arm.elf.packageBase ?= /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/arm/elf/
.PRECIOUS: $(XDCCFGDIR)/%.oe674
.PHONY: all,e674 .dlls,e674 .executables,e674 test,e674
all,e674: .executables,e674
.executables,e674: .libraries,e674
.executables,e674: .dlls,e674
.dlls,e674: .libraries,e674
.libraries,e674: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e674
	@$(ECHO) xdc .executables,e674
	@$(ECHO) xdc .libraries,e674
	@$(ECHO) xdc .dlls,e674

.PRECIOUS: $(XDCCFGDIR)/%.oem3
.PHONY: all,em3 .dlls,em3 .executables,em3 test,em3
all,em3: .executables,em3
.executables,em3: .libraries,em3
.executables,em3: .dlls,em3
.dlls,em3: .libraries,em3
.libraries,em3: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,em3
	@$(ECHO) xdc .executables,em3
	@$(ECHO) xdc .libraries,em3
	@$(ECHO) xdc .dlls,em3


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.syslink.samples.rtos.procMgr.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.syslink.samples.rtos.procMgr" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/package.ext.xml: package/package.cfg.xdc.inc
package/package.cfg.xdc.inc: $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.syslink.samples.rtos.procMgr $@

.libraries,e674 .libraries: lib/debug/ti.syslink.samples.rtos.procMgr.ae674

-include lib/debug/ti.syslink.samples.rtos.procMgr.ae674.mak
lib/debug/ti.syslink.samples.rtos.procMgr.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/ti.syslink.samples.rtos.procMgr/package/package_ti.syslink.samples.rtos.procMgr.oe674 package/lib/lib/debug/ti.syslink.samples.rtos.procMgr/ProcMgrApp.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/debug/ti.syslink.samples.rtos.procMgr/package/package_ti.syslink.samples.rtos.procMgr.oe674 package/lib/lib/debug/ti.syslink.samples.rtos.procMgr/ProcMgrApp.oe674 
lib/debug/ti.syslink.samples.rtos.procMgr.ae674: export C_DIR=
lib/debug/ti.syslink.samples.rtos.procMgr.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/debug/ti.syslink.samples.rtos.procMgr.ae674
.libraries,e674 .libraries: lib/release/ti.syslink.samples.rtos.procMgr.ae674

-include lib/release/ti.syslink.samples.rtos.procMgr.ae674.mak
lib/release/ti.syslink.samples.rtos.procMgr.ae674: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/ti.syslink.samples.rtos.procMgr/package/package_ti.syslink.samples.rtos.procMgr.oe674 package/lib/lib/release/ti.syslink.samples.rtos.procMgr/ProcMgrApp.oe674  into $@ ...
	$(ti.targets.elf.C674.rootDir)/bin/ar6x  rq $@   package/lib/lib/release/ti.syslink.samples.rtos.procMgr/package/package_ti.syslink.samples.rtos.procMgr.oe674 package/lib/lib/release/ti.syslink.samples.rtos.procMgr/ProcMgrApp.oe674 
lib/release/ti.syslink.samples.rtos.procMgr.ae674: export C_DIR=
lib/release/ti.syslink.samples.rtos.procMgr.ae674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

clean,e674 clean::
	-$(RM) lib/release/ti.syslink.samples.rtos.procMgr.ae674
.libraries,em3 .libraries: lib/debug/ti.syslink.samples.rtos.procMgr.aem3

-include lib/debug/ti.syslink.samples.rtos.procMgr.aem3.mak
lib/debug/ti.syslink.samples.rtos.procMgr.aem3: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/ti.syslink.samples.rtos.procMgr/package/package_ti.syslink.samples.rtos.procMgr.oem3 package/lib/lib/debug/ti.syslink.samples.rtos.procMgr/ProcMgrApp.oem3  into $@ ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/ar470  rq $@   package/lib/lib/debug/ti.syslink.samples.rtos.procMgr/package/package_ti.syslink.samples.rtos.procMgr.oem3 package/lib/lib/debug/ti.syslink.samples.rtos.procMgr/ProcMgrApp.oem3 
lib/debug/ti.syslink.samples.rtos.procMgr.aem3: export C_DIR=
lib/debug/ti.syslink.samples.rtos.procMgr.aem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

clean,em3 clean::
	-$(RM) lib/debug/ti.syslink.samples.rtos.procMgr.aem3
.libraries,em3 .libraries: lib/release/ti.syslink.samples.rtos.procMgr.aem3

-include lib/release/ti.syslink.samples.rtos.procMgr.aem3.mak
lib/release/ti.syslink.samples.rtos.procMgr.aem3: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/ti.syslink.samples.rtos.procMgr/package/package_ti.syslink.samples.rtos.procMgr.oem3 package/lib/lib/release/ti.syslink.samples.rtos.procMgr/ProcMgrApp.oem3  into $@ ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/ar470  rq $@   package/lib/lib/release/ti.syslink.samples.rtos.procMgr/package/package_ti.syslink.samples.rtos.procMgr.oem3 package/lib/lib/release/ti.syslink.samples.rtos.procMgr/ProcMgrApp.oem3 
lib/release/ti.syslink.samples.rtos.procMgr.aem3: export C_DIR=
lib/release/ti.syslink.samples.rtos.procMgr.aem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

clean,em3 clean::
	-$(RM) lib/release/ti.syslink.samples.rtos.procMgr.aem3
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
.PHONY: package_ti.syslink.samples.rtos.procMgr.oe674,copy
package_ti.syslink.samples.rtos.procMgr.oe674,copy : package_ti.syslink.samples.rtos.procMgr.oe674,0,copy package_ti.syslink.samples.rtos.procMgr.oe674,1,copy 
	@

package_ti.syslink.samples.rtos.procMgr.oe674,0,copy : package/lib/lib/debug/ti.syslink.samples.rtos.procMgr/package/package_ti.syslink.samples.rtos.procMgr.oe674
package_ti.syslink.samples.rtos.procMgr.oe674,1,copy : package/lib/lib/release/ti.syslink.samples.rtos.procMgr/package/package_ti.syslink.samples.rtos.procMgr.oe674
.PHONY: package_ti.syslink.samples.rtos.procMgr.se674,copy
package_ti.syslink.samples.rtos.procMgr.se674,copy : package_ti.syslink.samples.rtos.procMgr.se674,0,copy package_ti.syslink.samples.rtos.procMgr.se674,1,copy 
	@

package_ti.syslink.samples.rtos.procMgr.se674,0,copy : package/lib/lib/debug/ti.syslink.samples.rtos.procMgr/package/package_ti.syslink.samples.rtos.procMgr.se674
package_ti.syslink.samples.rtos.procMgr.se674,1,copy : package/lib/lib/release/ti.syslink.samples.rtos.procMgr/package/package_ti.syslink.samples.rtos.procMgr.se674
.PHONY: ProcMgrApp.oe674,copy
ProcMgrApp.oe674,copy : ProcMgrApp.oe674,0,copy ProcMgrApp.oe674,1,copy 
	@

ProcMgrApp.oe674,0,copy : package/lib/lib/debug/ti.syslink.samples.rtos.procMgr/ProcMgrApp.oe674
ProcMgrApp.oe674,1,copy : package/lib/lib/release/ti.syslink.samples.rtos.procMgr/ProcMgrApp.oe674
.PHONY: ProcMgrApp.se674,copy
ProcMgrApp.se674,copy : ProcMgrApp.se674,0,copy ProcMgrApp.se674,1,copy 
	@

ProcMgrApp.se674,0,copy : package/lib/lib/debug/ti.syslink.samples.rtos.procMgr/ProcMgrApp.se674
ProcMgrApp.se674,1,copy : package/lib/lib/release/ti.syslink.samples.rtos.procMgr/ProcMgrApp.se674
.PHONY: package_ti.syslink.samples.rtos.procMgr.oem3,copy
package_ti.syslink.samples.rtos.procMgr.oem3,copy : package_ti.syslink.samples.rtos.procMgr.oem3,0,copy package_ti.syslink.samples.rtos.procMgr.oem3,1,copy 
	@

package_ti.syslink.samples.rtos.procMgr.oem3,0,copy : package/lib/lib/debug/ti.syslink.samples.rtos.procMgr/package/package_ti.syslink.samples.rtos.procMgr.oem3
package_ti.syslink.samples.rtos.procMgr.oem3,1,copy : package/lib/lib/release/ti.syslink.samples.rtos.procMgr/package/package_ti.syslink.samples.rtos.procMgr.oem3
.PHONY: package_ti.syslink.samples.rtos.procMgr.sem3,copy
package_ti.syslink.samples.rtos.procMgr.sem3,copy : package_ti.syslink.samples.rtos.procMgr.sem3,0,copy package_ti.syslink.samples.rtos.procMgr.sem3,1,copy 
	@

package_ti.syslink.samples.rtos.procMgr.sem3,0,copy : package/lib/lib/debug/ti.syslink.samples.rtos.procMgr/package/package_ti.syslink.samples.rtos.procMgr.sem3
package_ti.syslink.samples.rtos.procMgr.sem3,1,copy : package/lib/lib/release/ti.syslink.samples.rtos.procMgr/package/package_ti.syslink.samples.rtos.procMgr.sem3
.PHONY: ProcMgrApp.oem3,copy
ProcMgrApp.oem3,copy : ProcMgrApp.oem3,0,copy ProcMgrApp.oem3,1,copy 
	@

ProcMgrApp.oem3,0,copy : package/lib/lib/debug/ti.syslink.samples.rtos.procMgr/ProcMgrApp.oem3
ProcMgrApp.oem3,1,copy : package/lib/lib/release/ti.syslink.samples.rtos.procMgr/ProcMgrApp.oem3
.PHONY: ProcMgrApp.sem3,copy
ProcMgrApp.sem3,copy : ProcMgrApp.sem3,0,copy ProcMgrApp.sem3,1,copy 
	@

ProcMgrApp.sem3,0,copy : package/lib/lib/debug/ti.syslink.samples.rtos.procMgr/ProcMgrApp.sem3
ProcMgrApp.sem3,1,copy : package/lib/lib/release/ti.syslink.samples.rtos.procMgr/ProcMgrApp.sem3

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti.syslink.samples.rtos.procMgr,src
ti.syslink.samples.rtos.procMgr,src.tar: package/package.bld.xml
ti.syslink.samples.rtos.procMgr,src.tar: package/package.ext.xml
ti.syslink.samples.rtos.procMgr,src.tar: package/package.rel.dot
ti.syslink.samples.rtos.procMgr,src.tar: package/build.cfg
ti.syslink.samples.rtos.procMgr,src.tar: package/package.xdc.inc
ti.syslink.samples.rtos.procMgr,src.tar: package/package.cfg.xdc.inc
ti.syslink.samples.rtos.procMgr,src.tar: lib/debug/ti.syslink.samples.rtos.procMgr.ae674
ti.syslink.samples.rtos.procMgr,src.tar: lib/release/ti.syslink.samples.rtos.procMgr.ae674
ti.syslink.samples.rtos.procMgr,src.tar: lib/debug/ti.syslink.samples.rtos.procMgr.aem3
ti.syslink.samples.rtos.procMgr,src.tar: lib/release/ti.syslink.samples.rtos.procMgr.aem3
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti.syslink.samples.rtos.procMgr,src.tar.dep
endif
package/rel/ti.syslink.samples.rtos.procMgr,src/ti/syslink/samples/rtos/procMgr/package/package.rel.xml:

ti.syslink.samples.rtos.procMgr,src.tar: package/rel/ti.syslink.samples.rtos.procMgr,src.xdc.inc package/rel/ti.syslink.samples.rtos.procMgr,src/ti/syslink/samples/rtos/procMgr/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti.syslink.samples.rtos.procMgr$(comma)src.xdc.inc,package/rel/ti.syslink.samples.rtos.procMgr$(comma)src.tar.dep)


release release,ti.syslink.samples.rtos.procMgr,src: all ti.syslink.samples.rtos.procMgr,src.tar
clean:: .clean
	-$(RM) ti.syslink.samples.rtos.procMgr,src.tar
	-$(RM) package/rel/ti.syslink.samples.rtos.procMgr,src.xdc.inc
	-$(RM) package/rel/ti.syslink.samples.rtos.procMgr,src.tar.dep


.PHONY: release,ti_syslink_samples_rtos_procMgr
ti_syslink_samples_rtos_procMgr.tar: package/package.bld.xml
ti_syslink_samples_rtos_procMgr.tar: package/package.ext.xml
ti_syslink_samples_rtos_procMgr.tar: package/package.rel.dot
ti_syslink_samples_rtos_procMgr.tar: package/build.cfg
ti_syslink_samples_rtos_procMgr.tar: package/package.xdc.inc
ti_syslink_samples_rtos_procMgr.tar: package/package.cfg.xdc.inc
ti_syslink_samples_rtos_procMgr.tar: lib/debug/ti.syslink.samples.rtos.procMgr.ae674
ti_syslink_samples_rtos_procMgr.tar: lib/release/ti.syslink.samples.rtos.procMgr.ae674
ti_syslink_samples_rtos_procMgr.tar: lib/debug/ti.syslink.samples.rtos.procMgr.aem3
ti_syslink_samples_rtos_procMgr.tar: lib/release/ti.syslink.samples.rtos.procMgr.aem3
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti_syslink_samples_rtos_procMgr.tar.dep
endif
package/rel/ti_syslink_samples_rtos_procMgr/ti/syslink/samples/rtos/procMgr/package/package.rel.xml:

ti_syslink_samples_rtos_procMgr.tar: package/rel/ti_syslink_samples_rtos_procMgr.xdc.inc package/rel/ti_syslink_samples_rtos_procMgr/ti/syslink/samples/rtos/procMgr/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_syslink_samples_rtos_procMgr.xdc.inc,package/rel/ti_syslink_samples_rtos_procMgr.tar.dep)


release release,ti_syslink_samples_rtos_procMgr: all ti_syslink_samples_rtos_procMgr.tar
clean:: .clean
	-$(RM) ti_syslink_samples_rtos_procMgr.tar
	-$(RM) package/rel/ti_syslink_samples_rtos_procMgr.xdc.inc
	-$(RM) package/rel/ti_syslink_samples_rtos_procMgr.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RMDIR) lib/

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard lib))
    $(shell $(MKDIR) lib)
endif
ifeq (,$(wildcard lib/debug))
    $(shell $(MKDIR) lib/debug)
endif
ifeq (,$(wildcard lib/release))
    $(shell $(MKDIR) lib/release)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib/lib))
    $(shell $(MKDIR) package/lib/lib)
endif
ifeq (,$(wildcard package/lib/lib/debug))
    $(shell $(MKDIR) package/lib/lib/debug)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.samples.rtos.procMgr))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.samples.rtos.procMgr)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti.syslink.samples.rtos.procMgr/package))
    $(shell $(MKDIR) package/lib/lib/debug/ti.syslink.samples.rtos.procMgr/package)
endif
ifeq (,$(wildcard package/lib/lib/release))
    $(shell $(MKDIR) package/lib/lib/release)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.samples.rtos.procMgr))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.samples.rtos.procMgr)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.syslink.samples.rtos.procMgr/package))
    $(shell $(MKDIR) package/lib/lib/release/ti.syslink.samples.rtos.procMgr/package)
endif
endif
clean::
	-$(RMDIR) package


clean:: 
	-$(RM) package/ti.syslink.samples.rtos.procMgr.pjt
