cmd_/home/sksung/work/udx/ch2/packages/dev_app/module/wifi/8821au_driver/hal/hal_mcc.o := /home/sksung/work/udx/ch2/packages/../ti_tools/linux_devkit/bin/arm-arago-linux-gnueabi-gcc -Wp,-MD,/home/sksung/work/udx/ch2/packages/dev_app/module/wifi/8821au_driver/hal/.hal_mcc.o.d  -nostdinc -isystem /home/sksung/work/udx/ch2/ti_tools/linux_devkit/bin/../lib/gcc/arm-arago-linux-gnueabi/4.5.3/include -I/home/sksung/work/udx/ch2/packages/psp/kernel/arch/arm/include -Iinclude  -include include/generated/autoconf.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-omap2/include -Iarch/arm/plat-omap/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Os -marm -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -mabi=aapcs-linux -mno-thumb-interwork -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -fno-omit-frame-pointer -fno-optimize-sibling-calls -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -O1 -Wno-unused-variable -Wno-unused-value -Wno-unused-label -Wno-unused-parameter -Wno-unused-function -Wno-unused -I/home/sksung/work/udx/ch2/packages/dev_app/module/wifi/8821au_driver/include -I/home/sksung/work/udx/ch2/packages/dev_app/module/wifi/8821au_driver/hal/phydm -I/home/sksung/work/udx/ch2/packages/dev_app/module/wifi/8821au_driver/platform -I/home/sksung/work/udx/ch2/packages/dev_app/module/wifi/8821au_driver/hal/btc -DCONFIG_RTL8821A -DCONFIG_MP_INCLUDED -DCONFIG_BT_COEXIST -DCONFIG_EFUSE_CONFIG_FILE -DEFUSE_MAP_PATH=\"/system/etc/wifi/wifi_efuse_8821au.map\" -DWIFIMAC_PATH=\"/data/wifimac.txt\" -DCONFIG_TRAFFIC_PROTECT -DCONFIG_LOAD_PHY_PARA_FROM_FILE -DREALTEK_CONFIG_PATH=\"\" -DCONFIG_TXPWR_BY_RATE_EN=0 -DCONFIG_TXPWR_LIMIT_EN=0 -DCONFIG_RTW_ADAPTIVITY_EN=0 -DCONFIG_RTW_ADAPTIVITY_MODE=0 -DCONFIG_BR_EXT '-DCONFIG_BR_EXT_BRNAME="'br0'"' -DCONFIG_RTW_NAPI -DCONFIG_RTW_GRO -DCONFIG_RTW_DEBUG -DRTW_LOG_LEVEL=4 -DDM_ODM_SUPPORT_TYPE=0x04 -DCONFIG_LITTLE_ENDIAN  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(hal_mcc)"  -D"KBUILD_MODNAME=KBUILD_STR(8821au)" -c -o /home/sksung/work/udx/ch2/packages/dev_app/module/wifi/8821au_driver/hal/.tmp_hal_mcc.o /home/sksung/work/udx/ch2/packages/dev_app/module/wifi/8821au_driver/hal/hal_mcc.c

deps_/home/sksung/work/udx/ch2/packages/dev_app/module/wifi/8821au_driver/hal/hal_mcc.o := \
  /home/sksung/work/udx/ch2/packages/dev_app/module/wifi/8821au_driver/hal/hal_mcc.c \
    $(wildcard include/config/mcc/mode.h) \
    $(wildcard include/config/mcc/mode/debug.h) \

/home/sksung/work/udx/ch2/packages/dev_app/module/wifi/8821au_driver/hal/hal_mcc.o: $(deps_/home/sksung/work/udx/ch2/packages/dev_app/module/wifi/8821au_driver/hal/hal_mcc.o)

$(deps_/home/sksung/work/udx/ch2/packages/dev_app/module/wifi/8821au_driver/hal/hal_mcc.o):
