#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = google.targets.arm.Bionic{1,0,4.4,3
#
ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/debug/auddec1_ti/package/package_ti.sdo.fc.ires.examples.codecs.auddec1.obnc.dep
endif

package/lib/lib/debug/auddec1_ti/package/package_ti.sdo.fc.ires.examples.codecs.auddec1.obnc: | .interfaces
package/lib/lib/debug/auddec1_ti/package/package_ti.sdo.fc.ires.examples.codecs.auddec1.obnc: package/package_ti.sdo.fc.ires.examples.codecs.auddec1.c lib/debug/auddec1_ti.abnc.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clbnc $< ...
	/db/rtree/install/trees/products/xdcprod/xdcprod-p43/product/Linux/xdctools_3_23_01_43/packages/google/targets/runh -h sanbud01.sanb.design.ti.com $(google.targets.arm.Bionic.rootDir)/bin/arm-eabi-gcc -c  -x c  -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -D_DEBUG_=1 -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_debug -Dxdc_bld__vers_1_0_4_4_3 -g -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/arch-arm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libstdc++/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/common -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/arch-arm -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include/arch/arm  $(XDCINCS)  -o $@ $<
	$(MKDEP) -o $@.dep -p package/lib/lib/debug/auddec1_ti/package/ -s obnc $< -C -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -D_DEBUG_=1 -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_debug -Dxdc_bld__vers_1_0_4_4_3 -g -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/arch-arm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libstdc++/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/common -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/arch-arm -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include/arch/arm  $(XDCINCS) 
	ls `dirname $@` > /dev/null
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/debug/auddec1_ti/package/package_ti.sdo.fc.ires.examples.codecs.auddec1.obnc: export LD_LIBRARY_PATH=

package/lib/lib/debug/auddec1_ti/package/package_ti.sdo.fc.ires.examples.codecs.auddec1.sbnc: | .interfaces
package/lib/lib/debug/auddec1_ti/package/package_ti.sdo.fc.ires.examples.codecs.auddec1.sbnc: package/package_ti.sdo.fc.ires.examples.codecs.auddec1.c lib/debug/auddec1_ti.abnc.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clbnc -S $< ...
	/db/rtree/install/trees/products/xdcprod/xdcprod-p43/product/Linux/xdctools_3_23_01_43/packages/google/targets/runh -h sanbud01.sanb.design.ti.com $(google.targets.arm.Bionic.rootDir)/bin/arm-eabi-gcc -c  -x c -S -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -D_DEBUG_=1 -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_debug -Dxdc_bld__vers_1_0_4_4_3 -g  $(XDCINCS)  -o $@ $<
	$(MKDEP) -o $@.dep -p package/lib/lib/debug/auddec1_ti/package/ -s obnc $< -C -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -D_DEBUG_=1 -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_debug -Dxdc_bld__vers_1_0_4_4_3 -g  $(XDCINCS) 
	ls `dirname $@` > /dev/null
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/debug/auddec1_ti/package/package_ti.sdo.fc.ires.examples.codecs.auddec1.sbnc: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/debug/auddec1_ti/auddec1_ti.obnc.dep
endif

package/lib/lib/debug/auddec1_ti/auddec1_ti.obnc: | .interfaces
package/lib/lib/debug/auddec1_ti/auddec1_ti.obnc: auddec1_ti.c lib/debug/auddec1_ti.abnc.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clbnc $< ...
	/db/rtree/install/trees/products/xdcprod/xdcprod-p43/product/Linux/xdctools_3_23_01_43/packages/google/targets/runh -h sanbud01.sanb.design.ti.com $(google.targets.arm.Bionic.rootDir)/bin/arm-eabi-gcc -c  -x c  -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -D_DEBUG_=1 -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_debug -Dxdc_bld__vers_1_0_4_4_3 -g -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/arch-arm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libstdc++/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/common -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/arch-arm -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include/arch/arm  $(XDCINCS)  -o $@ $<
	$(MKDEP) -o $@.dep -p package/lib/lib/debug/auddec1_ti/ -s obnc $< -C -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -D_DEBUG_=1 -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_debug -Dxdc_bld__vers_1_0_4_4_3 -g -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/arch-arm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libstdc++/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/common -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/arch-arm -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include/arch/arm  $(XDCINCS) 
	ls `dirname $@` > /dev/null
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/debug/auddec1_ti/auddec1_ti.obnc: export LD_LIBRARY_PATH=

package/lib/lib/debug/auddec1_ti/auddec1_ti.sbnc: | .interfaces
package/lib/lib/debug/auddec1_ti/auddec1_ti.sbnc: auddec1_ti.c lib/debug/auddec1_ti.abnc.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clbnc -S $< ...
	/db/rtree/install/trees/products/xdcprod/xdcprod-p43/product/Linux/xdctools_3_23_01_43/packages/google/targets/runh -h sanbud01.sanb.design.ti.com $(google.targets.arm.Bionic.rootDir)/bin/arm-eabi-gcc -c  -x c -S -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -D_DEBUG_=1 -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_debug -Dxdc_bld__vers_1_0_4_4_3 -g  $(XDCINCS)  -o $@ $<
	$(MKDEP) -o $@.dep -p package/lib/lib/debug/auddec1_ti/ -s obnc $< -C -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -D_DEBUG_=1 -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_debug -Dxdc_bld__vers_1_0_4_4_3 -g  $(XDCINCS) 
	ls `dirname $@` > /dev/null
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/debug/auddec1_ti/auddec1_ti.sbnc: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/debug/auddec1_ti/auddec1_ti_ires.obnc.dep
endif

package/lib/lib/debug/auddec1_ti/auddec1_ti_ires.obnc: | .interfaces
package/lib/lib/debug/auddec1_ti/auddec1_ti_ires.obnc: auddec1_ti_ires.c lib/debug/auddec1_ti.abnc.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clbnc $< ...
	/db/rtree/install/trees/products/xdcprod/xdcprod-p43/product/Linux/xdctools_3_23_01_43/packages/google/targets/runh -h sanbud01.sanb.design.ti.com $(google.targets.arm.Bionic.rootDir)/bin/arm-eabi-gcc -c  -x c  -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -D_DEBUG_=1 -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_debug -Dxdc_bld__vers_1_0_4_4_3 -g -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/arch-arm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libstdc++/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/common -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/arch-arm -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include/arch/arm  $(XDCINCS)  -o $@ $<
	$(MKDEP) -o $@.dep -p package/lib/lib/debug/auddec1_ti/ -s obnc $< -C -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -D_DEBUG_=1 -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_debug -Dxdc_bld__vers_1_0_4_4_3 -g -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/arch-arm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libstdc++/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/common -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libc/kernel/arch-arm -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include -I/db/toolsrc/library/tools/vendors/android/rowboat/ti814x/20111011/bionic/libm/include/arch/arm  $(XDCINCS) 
	ls `dirname $@` > /dev/null
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/debug/auddec1_ti/auddec1_ti_ires.obnc: export LD_LIBRARY_PATH=

package/lib/lib/debug/auddec1_ti/auddec1_ti_ires.sbnc: | .interfaces
package/lib/lib/debug/auddec1_ti/auddec1_ti_ires.sbnc: auddec1_ti_ires.c lib/debug/auddec1_ti.abnc.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clbnc -S $< ...
	/db/rtree/install/trees/products/xdcprod/xdcprod-p43/product/Linux/xdctools_3_23_01_43/packages/google/targets/runh -h sanbud01.sanb.design.ti.com $(google.targets.arm.Bionic.rootDir)/bin/arm-eabi-gcc -c  -x c -S -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -D_DEBUG_=1 -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_debug -Dxdc_bld__vers_1_0_4_4_3 -g  $(XDCINCS)  -o $@ $<
	$(MKDEP) -o $@.dep -p package/lib/lib/debug/auddec1_ti/ -s obnc $< -C -fPIC -Wunused -Wall -fno-strict-aliasing  -march=armv5t -fno-short-enums  -Dfar=  -D_ANDROID_ -D_DEBUG_=1 -Dxdc_target_name__=Bionic -Dxdc_target_types__=google/targets/arm/std.h -Dxdc_bld__profile_debug -Dxdc_bld__vers_1_0_4_4_3 -g  $(XDCINCS) 
	ls `dirname $@` > /dev/null
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/debug/auddec1_ti/auddec1_ti_ires.sbnc: export LD_LIBRARY_PATH=

clean,bnc ::
	-$(RM) package/lib/lib/debug/auddec1_ti/package/package_ti.sdo.fc.ires.examples.codecs.auddec1.obnc
	-$(RM) package/lib/lib/debug/auddec1_ti/auddec1_ti.obnc
	-$(RM) package/lib/lib/debug/auddec1_ti/auddec1_ti_ires.obnc
	-$(RM) package/lib/lib/debug/auddec1_ti/package/package_ti.sdo.fc.ires.examples.codecs.auddec1.sbnc
	-$(RM) package/lib/lib/debug/auddec1_ti/auddec1_ti.sbnc
	-$(RM) package/lib/lib/debug/auddec1_ti/auddec1_ti_ires.sbnc

lib/debug/auddec1_ti.abnc: package/lib/lib/debug/auddec1_ti/package/package_ti.sdo.fc.ires.examples.codecs.auddec1.obnc package/lib/lib/debug/auddec1_ti/auddec1_ti.obnc package/lib/lib/debug/auddec1_ti/auddec1_ti_ires.obnc lib/debug/auddec1_ti.abnc.mak

clean::
	-$(RM) lib/debug/auddec1_ti.abnc.mak
