.bd B 3
.TH dis470 1 "May 07, 2012" "TI Tools" "TI Code Generation Tools"
.SH NAME
dis470 - Disassembler
.SH SYNOPSIS
.B dis470
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
The disassembler translates machine language object files into human readable assembly source code.
.SH OPTIONS
The following options are accepted by this tool:
.SS Section Selection Options:
.SS
.TP
-1
Disassemble all sections, process .cinit sections
.TP
-d
Do not display DATA sections
.TP
-t
Do not display TEXT sections
.TP
-y
Display copy tables and the sections copied
.SS Format Altering Options:
.SS
.TP
-a
Do not print ADDRESS with label names within instructions
.TP
-b
Display data as BYTES instead of words
.TP
-e
Display integer values in hex
.TP
-I
Disassemble TEXT sections as DATA
.TP
-i
Disassemble DATA sections as TEXT
.TP
-L
Show both load and runtime addresses if different
.TP
-q
QUIET Operation
.TP
-qq
Really Quiet -- suppresses all headers
.TP
-r
Use raw register IDs (R0, R1, etc...)
.TP
-s
Suppress printing address and data words
.TP
--ual
Display assembly in unified assembly language
.SS Miscellaneous Options:
.SS
.TP
-h
Display a help message that includes usage and option information
.SH EXIT STATUS
The following error values are returned:
.PD 0
.TP 10
.B 0
Successful completion.
.TP
.B >0
Unsuccessful completion; an error occured.
.PD
.SH COPYRIGHT
.TP
Copyright (c) 2012, Texas Instruments, Inc.
