.bd B 3
.TH libinfo470 1 "May 07, 2012" "TI Tools" "TI Code Generation Tools"
.SH NAME
libinfo470 - Library Information Archiver
.SH SYNOPSIS
.B libinfo470
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
Builds an archive of information about available libraries.
This tool should be invoked via the shell (cl).  See the shell documentation for information on shell options.
.SH COPYRIGHT
.TP
Copyright (c) 2012, Texas Instruments, Inc.
