/*
 *  Copyright 2012 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) google.targets; 1, 0, 0,22; 2-10-2012 11:27:35; /db/ztree/library/trees/xdctargets/xdctargets-f18x/src/ xlibrary

 */

