#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = ti/syslink/samples/rtos/ti81xx/frameq_ti81xx
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCPKGS = $(call pkgsearch,ti/bios/include )
XDCINCS += $(if $(XDCPKGS),-I$(subst $(space), -I,$(XDCPKGS)))
IMPORTPATH += $(if $(XDCPKGS),;$(subst $(space),;,$(XDCPKGS)))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/include/utils.tci:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/include/utils.tci
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/xdc.tci:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/xdc.tci
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/template.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/template.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/om2.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/om2.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/xmlgen.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/xmlgen.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/xmlgen2.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/xmlgen2.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/IPackage.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/IPackage.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/package.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/package.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/services/global/Clock.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/services/global/Clock.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/services/global/Trace.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/services/global/Trace.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/bld.js:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/bld.js
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/BuildEnvironment.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/PackageContents.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/PackageContents.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/_gen.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/_gen.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Library.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Library.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Executable.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Executable.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Repository.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Repository.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Configuration.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Configuration.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Script.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Script.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Manifest.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Manifest.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Utils.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/Utils.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/ITarget.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/ITarget.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/ITarget2.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/ITarget2.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/ITargetFilter.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/ITargetFilter.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/package.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/xdc/bld/package.xs
/home/sksung/work/udx/ch2/ti_tools/syslink_2_10_06_28/packages/_config.bld:
package.mak: /home/sksung/work/udx/ch2/ti_tools/syslink_2_10_06_28/packages/_config.bld
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/ITarget.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/ITarget.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/C28_large.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/C28_large.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/C28_float.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/C28_float.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/package.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/package.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/elf/ITarget.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/elf/ITarget.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/elf/TMS470.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/elf/TMS470.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/elf/package.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/elf/package.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/arm/IArm.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/arm/IArm.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/arm/package.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/arm/package.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/arm/elf/IArm.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/arm/elf/IArm.xs
/home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/arm/elf/package.xs:
package.mak: /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/arm/elf/package.xs
package.mak: package.bld
/home/sksung/work/udx/ch2/ti_tools/syslink_2_10_06_28/packages/ti/syslink/buildutils/rtos/buildScripts/test.bld:
package.mak: /home/sksung/work/udx/ch2/ti_tools/syslink_2_10_06_28/packages/ti/syslink/buildutils/rtos/buildScripts/test.bld
endif

ti.targets.elf.C674.rootDir ?= /home/sksung/work/udx/ch2/packages/../ti_tools/cgt6x_7_3_5
ti.targets.elf.packageBase ?= /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/elf/
ti.targets.arm.elf.M3.rootDir ?= /home/sksung/work/udx/ch2/packages/../ti_tools/cgt470_4_9_5
ti.targets.arm.elf.packageBase ?= /home/sksung/work/udx/ch2/ti_tools/xdctools_3_23_03_53/packages/ti/targets/arm/elf/
.PRECIOUS: $(XDCCFGDIR)/%.oe674
.PHONY: all,e674 .dlls,e674 .executables,e674 test,e674
all,e674: .executables,e674
.executables,e674: .libraries,e674
.executables,e674: .dlls,e674
.dlls,e674: .libraries,e674
.libraries,e674: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e674
	@$(ECHO) xdc .executables,e674
	@$(ECHO) xdc .libraries,e674
	@$(ECHO) xdc .dlls,e674

.PRECIOUS: $(XDCCFGDIR)/%.oem3
.PHONY: all,em3 .dlls,em3 .executables,em3 test,em3
all,em3: .executables,em3
.executables,em3: .libraries,em3
.executables,em3: .dlls,em3
.dlls,em3: .libraries,em3
.libraries,em3: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,em3
	@$(ECHO) xdc .executables,em3
	@$(ECHO) xdc .libraries,em3
	@$(ECHO) xdc .dlls,em3


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.syslink.samples.rtos.ti81xx.frameq_ti81xx.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.syslink.samples.rtos.ti81xx.frameq_ti81xx" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.dlls,e674 .dlls: ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.pe674

-include package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp_pe674.mak
-include package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp_pe674.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp_pe674.dep
endif
ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.pe674: package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp_pe674.xdl
	@


ifeq (,$(wildcard .libraries,e674))
ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.pe674 package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp_pe674.c: .libraries,e674
endif

package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp_pe674.c package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp_pe674.h package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp_pe674.xdl: override _PROG_NAME := ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.xe674
package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp_pe674.c: package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp_pe674.cfg

clean:: clean,e674
	-$(RM) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp_pe674.cfg
	-$(RM) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp_pe674.dep
	-$(RM) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp_pe674.c
	-$(RM) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp_pe674.xdc.inc

clean,e674::
	-$(RM) ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.pe674
.dlls,em3 .dlls: ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.pem3

-include package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3_pem3.mak
-include package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3_pem3.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3_pem3.dep
endif
ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.pem3: package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3_pem3.xdl
	@


ifeq (,$(wildcard .libraries,em3))
ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.pem3 package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3_pem3.c: .libraries,em3
endif

package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3_pem3.c package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3_pem3.h package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3_pem3.xdl: override _PROG_NAME := ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.xem3
package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3_pem3.c: package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3_pem3.cfg

clean:: clean,em3
	-$(RM) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3_pem3.cfg
	-$(RM) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3_pem3.dep
	-$(RM) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3_pem3.c
	-$(RM) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3_pem3.xdc.inc

clean,em3::
	-$(RM) ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.pem3
.dlls,em3 .dlls: ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.pem3

-include package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3_pem3.mak
-include package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3_pem3.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3_pem3.dep
endif
ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.pem3: package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3_pem3.xdl
	@


ifeq (,$(wildcard .libraries,em3))
ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.pem3 package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3_pem3.c: .libraries,em3
endif

package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3_pem3.c package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3_pem3.h package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3_pem3.xdl: override _PROG_NAME := ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.xem3
package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3_pem3.c: package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3_pem3.cfg

clean:: clean,em3
	-$(RM) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3_pem3.cfg
	-$(RM) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3_pem3.dep
	-$(RM) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3_pem3.c
	-$(RM) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3_pem3.xdc.inc

clean,em3::
	-$(RM) ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.pem3
.executables,e674 .executables: ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.xe674

ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.xe674: |ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.pe674

-include package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.xe674.mak
ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.xe674: package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp_pe674.oe674 
	$(RM) $@
	@$(MSG) lnke674 $@ ...
	$(RM) $(XDCCFGDIR)/$@.map
	$(ti.targets.elf.C674.rootDir)/bin/lnk6x -w -q -u _c_int00 -fs $(XDCCFGDIR)$(dir $@)  -q -o $@ package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp_pe674.oe674  package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp/FrameQ_ti81xx_dsp.oe674  package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp_pe674.xdl --abi=eabi -c -m $(XDCCFGDIR)/$@.map -l $(ti.targets.elf.C674.rootDir)/lib/rts6740_elf.lib
	
ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.xe674: export C_DIR=
ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.xe674: PATH:=$(ti.targets.elf.C674.rootDir)/bin/:$(PATH)

test,e674 test regress.test: regress.test,e674

ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.test: ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.xe674.regress.test
regress.test,e674: ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.xe674.regress.test
ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.xe674.regress.test:: ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.xe674
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.xe674.regress.test
else
	@$(XDCTEST.MSG) running $<  ...
	-$(RM) ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/.tmp,frameq_ti81xx_dsp.xe674,0
	$(call EXEC.ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.xe674, -t 60) $(XDCTEST.REDIRECT) ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/.tmp,frameq_ti81xx_dsp.xe674,0
	$(CMP) ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/.tmp,frameq_ti81xx_dsp.xe674,0 golden/frameq_ti81xx_dsp.k
	@$(MSG) test passed [$< ].

	$(RM) ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/.tmp,frameq_ti81xx_dsp.xe674,0
endif

ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.test test,e674 test: ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.xe674.test

ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.xe674.test:: ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.xe674
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.xe674.test
else
	@$(MSG) running $<  ...
	$(call EXEC.ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.xe674, -t 60) 
endif

clean,e674::
	-$(RM) ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/.tmp,frameq_ti81xx_dsp.xe674,1,*


clean:: clean,e674

clean,e674::
	-$(RM) ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp.xe674
clean:: 
	-$(RM) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp_pe674.pjt
.executables,em3 .executables: ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.xem3

ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.xem3: |ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.pem3

-include package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.xem3.mak
ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.xem3: package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3_pem3.oem3 
	$(RM) $@
	@$(MSG) lnkem3 $@ ...
	$(RM) $(XDCCFGDIR)/$@.map
	$(ti.targets.arm.elf.M3.rootDir)/bin/lnk470 -w -q -u _c_int00 -fs $(XDCCFGDIR)$(dir $@)  -q -o $@ package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3_pem3.oem3  package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3/FrameQ_ti81xx_videom3.oem3  package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3_pem3.xdl --silicon_version=7M3 --strict_compatibility=on -c -m $(XDCCFGDIR)/$@.map  -l $(ti.targets.arm.elf.M3.rootDir)/lib/rtsv7M3_T_le_eabi.lib
	
ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.xem3: export C_DIR=
ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.xem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

test,em3 test regress.test: regress.test,em3

ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.test: ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.xem3.regress.test
regress.test,em3: ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.xem3.regress.test
ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.xem3.regress.test:: ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.xem3
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.xem3.regress.test
else
	@$(XDCTEST.MSG) running $<  ...
	-$(RM) ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/.tmp,frameq_ti81xx_videom3.xem3,0
	$(call EXEC.ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.xem3, -t 60) $(XDCTEST.REDIRECT) ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/.tmp,frameq_ti81xx_videom3.xem3,0
	$(CMP) ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/.tmp,frameq_ti81xx_videom3.xem3,0 golden/frameq_ti81xx_videom3.k
	@$(MSG) test passed [$< ].

	$(RM) ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/.tmp,frameq_ti81xx_videom3.xem3,0
endif

ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.test test,em3 test: ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.xem3.test

ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.xem3.test:: ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.xem3
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.xem3.test
else
	@$(MSG) running $<  ...
	$(call EXEC.ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.xem3, -t 60) 
endif

clean,em3::
	-$(RM) ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/.tmp,frameq_ti81xx_videom3.xem3,1,*


clean:: clean,em3

clean,em3::
	-$(RM) ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3.xem3
clean:: 
	-$(RM) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3_pem3.pjt
.executables,em3 .executables: ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.xem3

ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.xem3: |ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.pem3

-include package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.xem3.mak
ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.xem3: package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3_pem3.oem3 
	$(RM) $@
	@$(MSG) lnkem3 $@ ...
	$(RM) $(XDCCFGDIR)/$@.map
	$(ti.targets.arm.elf.M3.rootDir)/bin/lnk470 -w -q -u _c_int00 -fs $(XDCCFGDIR)$(dir $@)  -q -o $@ package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3_pem3.oem3  package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3/FrameQ_ti81xx_vpssm3.oem3  package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3_pem3.xdl --silicon_version=7M3 --strict_compatibility=on -c -m $(XDCCFGDIR)/$@.map  -l $(ti.targets.arm.elf.M3.rootDir)/lib/rtsv7M3_T_le_eabi.lib
	
ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.xem3: export C_DIR=
ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.xem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

test,em3 test regress.test: regress.test,em3

ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.test: ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.xem3.regress.test
regress.test,em3: ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.xem3.regress.test
ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.xem3.regress.test:: ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.xem3
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.xem3.regress.test
else
	@$(XDCTEST.MSG) running $<  ...
	-$(RM) ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/.tmp,frameq_ti81xx_vpssm3.xem3,0
	$(call EXEC.ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.xem3, -t 60) $(XDCTEST.REDIRECT) ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/.tmp,frameq_ti81xx_vpssm3.xem3,0
	$(CMP) ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/.tmp,frameq_ti81xx_vpssm3.xem3,0 golden/frameq_ti81xx_vpssm3.k
	@$(MSG) test passed [$< ].

	$(RM) ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/.tmp,frameq_ti81xx_vpssm3.xem3,0
endif

ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.test test,em3 test: ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.xem3.test

ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.xem3.test:: ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.xem3
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.xem3.test
else
	@$(MSG) running $<  ...
	$(call EXEC.ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.xem3, -t 60) 
endif

clean,em3::
	-$(RM) ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/.tmp,frameq_ti81xx_vpssm3.xem3,1,*


clean:: clean,em3

clean,em3::
	-$(RM) ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3.xem3
clean:: 
	-$(RM) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3_pem3.pjt
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
frameq_ti81xx_dsp_pe674.oe674,copy : package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp_pe674.oe674
frameq_ti81xx_dsp_pe674.se674,copy : package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp_pe674.se674
frameq_ti81xx_videom3_pem3.oem3,copy : package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3_pem3.oem3
frameq_ti81xx_videom3_pem3.sem3,copy : package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3_pem3.sem3
frameq_ti81xx_vpssm3_pem3.oem3,copy : package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3_pem3.oem3
frameq_ti81xx_vpssm3_pem3.sem3,copy : package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3_pem3.sem3
FrameQ_ti81xx_dsp.oe674,copy : package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp/FrameQ_ti81xx_dsp.oe674
FrameQ_ti81xx_dsp.se674,copy : package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp/FrameQ_ti81xx_dsp.se674
FrameQ_ti81xx_videom3.oem3,copy : package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3/FrameQ_ti81xx_videom3.oem3
FrameQ_ti81xx_videom3.sem3,copy : package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3/FrameQ_ti81xx_videom3.sem3
FrameQ_ti81xx_vpssm3.oem3,copy : package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3/FrameQ_ti81xx_vpssm3.oem3
FrameQ_ti81xx_vpssm3.sem3,copy : package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3/FrameQ_ti81xx_vpssm3.sem3

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti.syslink.samples.rtos.ti81xx.frameq_ti81xx,src
ti.syslink.samples.rtos.ti81xx.frameq_ti81xx,src.tar: package/package.bld.xml
ti.syslink.samples.rtos.ti81xx.frameq_ti81xx,src.tar: package/package.ext.xml
ti.syslink.samples.rtos.ti81xx.frameq_ti81xx,src.tar: package/package.rel.dot
ti.syslink.samples.rtos.ti81xx.frameq_ti81xx,src.tar: package/build.cfg
ti.syslink.samples.rtos.ti81xx.frameq_ti81xx,src.tar: package/package.xdc.inc
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti.syslink.samples.rtos.ti81xx.frameq_ti81xx,src.tar.dep
endif
package/rel/ti.syslink.samples.rtos.ti81xx.frameq_ti81xx,src/ti/syslink/samples/rtos/ti81xx/frameq_ti81xx/package/package.rel.xml:

ti.syslink.samples.rtos.ti81xx.frameq_ti81xx,src.tar: package/rel/ti.syslink.samples.rtos.ti81xx.frameq_ti81xx,src.xdc.inc package/rel/ti.syslink.samples.rtos.ti81xx.frameq_ti81xx,src/ti/syslink/samples/rtos/ti81xx/frameq_ti81xx/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti.syslink.samples.rtos.ti81xx.frameq_ti81xx$(comma)src.xdc.inc,package/rel/ti.syslink.samples.rtos.ti81xx.frameq_ti81xx$(comma)src.tar.dep)


release release,ti.syslink.samples.rtos.ti81xx.frameq_ti81xx,src: all ti.syslink.samples.rtos.ti81xx.frameq_ti81xx,src.tar
clean:: .clean
	-$(RM) ti.syslink.samples.rtos.ti81xx.frameq_ti81xx,src.tar
	-$(RM) package/rel/ti.syslink.samples.rtos.ti81xx.frameq_ti81xx,src.xdc.inc
	-$(RM) package/rel/ti.syslink.samples.rtos.ti81xx.frameq_ti81xx,src.tar.dep


.PHONY: release,ti_syslink_samples_rtos_ti81xx_frameq_ti81xx
ti_syslink_samples_rtos_ti81xx_frameq_ti81xx.tar: package/package.bld.xml
ti_syslink_samples_rtos_ti81xx_frameq_ti81xx.tar: package/package.ext.xml
ti_syslink_samples_rtos_ti81xx_frameq_ti81xx.tar: package/package.rel.dot
ti_syslink_samples_rtos_ti81xx_frameq_ti81xx.tar: package/build.cfg
ti_syslink_samples_rtos_ti81xx_frameq_ti81xx.tar: package/package.xdc.inc
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti_syslink_samples_rtos_ti81xx_frameq_ti81xx.tar.dep
endif
package/rel/ti_syslink_samples_rtos_ti81xx_frameq_ti81xx/ti/syslink/samples/rtos/ti81xx/frameq_ti81xx/package/package.rel.xml:

ti_syslink_samples_rtos_ti81xx_frameq_ti81xx.tar: package/rel/ti_syslink_samples_rtos_ti81xx_frameq_ti81xx.xdc.inc package/rel/ti_syslink_samples_rtos_ti81xx_frameq_ti81xx/ti/syslink/samples/rtos/ti81xx/frameq_ti81xx/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_syslink_samples_rtos_ti81xx_frameq_ti81xx.xdc.inc,package/rel/ti_syslink_samples_rtos_ti81xx_frameq_ti81xx.tar.dep)


release release,ti_syslink_samples_rtos_ti81xx_frameq_ti81xx: all ti_syslink_samples_rtos_ti81xx_frameq_ti81xx.tar
clean:: .clean
	-$(RM) ti_syslink_samples_rtos_ti81xx_frameq_ti81xx.tar
	-$(RM) package/rel/ti_syslink_samples_rtos_ti81xx_frameq_ti81xx.xdc.inc
	-$(RM) package/rel/ti_syslink_samples_rtos_ti81xx_frameq_ti81xx.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RMDIR) ti_syslink_samples_rtos_platforms_ti816x_videom3/
	-$(RMDIR) ti_syslink_samples_rtos_platforms_ti816x_vpssm3/
	-$(RMDIR) ti_syslink_samples_rtos_platforms_ti816x_dsp/
	-$(RMDIR) ti_syslink_samples_rtos_platforms_ti814x_videom3/
	-$(RMDIR) ti_syslink_samples_rtos_platforms_ti814x_vpssm3/
	-$(RMDIR) ti_syslink_samples_rtos_platforms_ti814x_dsp/

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard ti_syslink_samples_rtos_platforms_ti814x_dsp))
    $(shell $(MKDIR) ti_syslink_samples_rtos_platforms_ti814x_dsp)
endif
ifeq (,$(wildcard ti_syslink_samples_rtos_platforms_ti814x_dsp/debug))
    $(shell $(MKDIR) ti_syslink_samples_rtos_platforms_ti814x_dsp/debug)
endif
ifeq (,$(wildcard ti_syslink_samples_rtos_platforms_ti814x_videom3))
    $(shell $(MKDIR) ti_syslink_samples_rtos_platforms_ti814x_videom3)
endif
ifeq (,$(wildcard ti_syslink_samples_rtos_platforms_ti814x_videom3/debug))
    $(shell $(MKDIR) ti_syslink_samples_rtos_platforms_ti814x_videom3/debug)
endif
ifeq (,$(wildcard ti_syslink_samples_rtos_platforms_ti814x_vpssm3))
    $(shell $(MKDIR) ti_syslink_samples_rtos_platforms_ti814x_vpssm3)
endif
ifeq (,$(wildcard ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug))
    $(shell $(MKDIR) ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp))
    $(shell $(MKDIR) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp)
endif
ifeq (,$(wildcard package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug))
    $(shell $(MKDIR) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug)
endif
ifeq (,$(wildcard package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3))
    $(shell $(MKDIR) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3)
endif
ifeq (,$(wildcard package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug))
    $(shell $(MKDIR) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug)
endif
ifeq (,$(wildcard package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3))
    $(shell $(MKDIR) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3)
endif
ifeq (,$(wildcard package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug))
    $(shell $(MKDIR) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug)
endif
ifeq (,$(wildcard package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp))
    $(shell $(MKDIR) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_dsp/debug/frameq_ti81xx_dsp)
endif
ifeq (,$(wildcard package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3))
    $(shell $(MKDIR) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_videom3/debug/frameq_ti81xx_videom3)
endif
ifeq (,$(wildcard package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3))
    $(shell $(MKDIR) package/cfg/ti_syslink_samples_rtos_platforms_ti814x_vpssm3/debug/frameq_ti81xx_vpssm3)
endif
endif
clean::
	-$(RMDIR) package


clean:: 
	-$(RM) package/ti.syslink.samples.rtos.ti81xx.frameq_ti81xx.pjt
