/*
 *  Do not modify this file; it is automatically 
 *  generated and any modifications will be overwritten.
 *
 * @(#) xdc-y21
 */

#ifndef ti_sdo_xdcruntime_linux__
#define ti_sdo_xdcruntime_linux__


/*
 * ======== module ti.sdo.xdcruntime.linux.GateThreadSupport ========
 */

typedef struct ti_sdo_xdcruntime_linux_GateThreadSupport_Fxns__ ti_sdo_xdcruntime_linux_GateThreadSupport_Fxns__;
typedef const ti_sdo_xdcruntime_linux_GateThreadSupport_Fxns__* ti_sdo_xdcruntime_linux_GateThreadSupport_Module;
typedef struct ti_sdo_xdcruntime_linux_GateThreadSupport_Params ti_sdo_xdcruntime_linux_GateThreadSupport_Params;
typedef struct ti_sdo_xdcruntime_linux_GateThreadSupport_Object ti_sdo_xdcruntime_linux_GateThreadSupport_Object;
typedef struct ti_sdo_xdcruntime_linux_GateThreadSupport_Struct ti_sdo_xdcruntime_linux_GateThreadSupport_Struct;
typedef ti_sdo_xdcruntime_linux_GateThreadSupport_Object* ti_sdo_xdcruntime_linux_GateThreadSupport_Handle;
typedef struct ti_sdo_xdcruntime_linux_GateThreadSupport_Object__ ti_sdo_xdcruntime_linux_GateThreadSupport_Instance_State;
typedef ti_sdo_xdcruntime_linux_GateThreadSupport_Object* ti_sdo_xdcruntime_linux_GateThreadSupport_Instance;

/*
 * ======== module ti.sdo.xdcruntime.linux.GateProcessSupport ========
 */

typedef struct ti_sdo_xdcruntime_linux_GateProcessSupport_Fxns__ ti_sdo_xdcruntime_linux_GateProcessSupport_Fxns__;
typedef const ti_sdo_xdcruntime_linux_GateProcessSupport_Fxns__* ti_sdo_xdcruntime_linux_GateProcessSupport_Module;
typedef struct ti_sdo_xdcruntime_linux_GateProcessSupport_Params ti_sdo_xdcruntime_linux_GateProcessSupport_Params;
typedef struct ti_sdo_xdcruntime_linux_GateProcessSupport_Object ti_sdo_xdcruntime_linux_GateProcessSupport_Object;
typedef struct ti_sdo_xdcruntime_linux_GateProcessSupport_Struct ti_sdo_xdcruntime_linux_GateProcessSupport_Struct;
typedef ti_sdo_xdcruntime_linux_GateProcessSupport_Object* ti_sdo_xdcruntime_linux_GateProcessSupport_Handle;
typedef struct ti_sdo_xdcruntime_linux_GateProcessSupport_Object__ ti_sdo_xdcruntime_linux_GateProcessSupport_Instance_State;
typedef ti_sdo_xdcruntime_linux_GateProcessSupport_Object* ti_sdo_xdcruntime_linux_GateProcessSupport_Instance;

/*
 * ======== module ti.sdo.xdcruntime.linux.SemThreadSupport ========
 */

typedef struct ti_sdo_xdcruntime_linux_SemThreadSupport_Module_State ti_sdo_xdcruntime_linux_SemThreadSupport_Module_State;
typedef struct ti_sdo_xdcruntime_linux_SemThreadSupport_Fxns__ ti_sdo_xdcruntime_linux_SemThreadSupport_Fxns__;
typedef const ti_sdo_xdcruntime_linux_SemThreadSupport_Fxns__* ti_sdo_xdcruntime_linux_SemThreadSupport_Module;
typedef struct ti_sdo_xdcruntime_linux_SemThreadSupport_Params ti_sdo_xdcruntime_linux_SemThreadSupport_Params;
typedef struct ti_sdo_xdcruntime_linux_SemThreadSupport_Object ti_sdo_xdcruntime_linux_SemThreadSupport_Object;
typedef struct ti_sdo_xdcruntime_linux_SemThreadSupport_Struct ti_sdo_xdcruntime_linux_SemThreadSupport_Struct;
typedef ti_sdo_xdcruntime_linux_SemThreadSupport_Object* ti_sdo_xdcruntime_linux_SemThreadSupport_Handle;
typedef struct ti_sdo_xdcruntime_linux_SemThreadSupport_Object__ ti_sdo_xdcruntime_linux_SemThreadSupport_Instance_State;
typedef ti_sdo_xdcruntime_linux_SemThreadSupport_Object* ti_sdo_xdcruntime_linux_SemThreadSupport_Instance;

/*
 * ======== module ti.sdo.xdcruntime.linux.SemProcessSupport ========
 */

typedef struct ti_sdo_xdcruntime_linux_SemProcessSupport_Fxns__ ti_sdo_xdcruntime_linux_SemProcessSupport_Fxns__;
typedef const ti_sdo_xdcruntime_linux_SemProcessSupport_Fxns__* ti_sdo_xdcruntime_linux_SemProcessSupport_Module;
typedef struct ti_sdo_xdcruntime_linux_SemProcessSupport_Params ti_sdo_xdcruntime_linux_SemProcessSupport_Params;
typedef struct ti_sdo_xdcruntime_linux_SemProcessSupport_Object ti_sdo_xdcruntime_linux_SemProcessSupport_Object;
typedef struct ti_sdo_xdcruntime_linux_SemProcessSupport_Struct ti_sdo_xdcruntime_linux_SemProcessSupport_Struct;
typedef ti_sdo_xdcruntime_linux_SemProcessSupport_Object* ti_sdo_xdcruntime_linux_SemProcessSupport_Handle;
typedef struct ti_sdo_xdcruntime_linux_SemProcessSupport_Object__ ti_sdo_xdcruntime_linux_SemProcessSupport_Instance_State;
typedef ti_sdo_xdcruntime_linux_SemProcessSupport_Object* ti_sdo_xdcruntime_linux_SemProcessSupport_Instance;

/*
 * ======== module ti.sdo.xdcruntime.linux.ThreadSupport ========
 */

typedef struct ti_sdo_xdcruntime_linux_ThreadSupport_Module_State ti_sdo_xdcruntime_linux_ThreadSupport_Module_State;
typedef struct ti_sdo_xdcruntime_linux_ThreadSupport_Fxns__ ti_sdo_xdcruntime_linux_ThreadSupport_Fxns__;
typedef const ti_sdo_xdcruntime_linux_ThreadSupport_Fxns__* ti_sdo_xdcruntime_linux_ThreadSupport_Module;
typedef struct ti_sdo_xdcruntime_linux_ThreadSupport_Params ti_sdo_xdcruntime_linux_ThreadSupport_Params;
typedef struct ti_sdo_xdcruntime_linux_ThreadSupport_Object ti_sdo_xdcruntime_linux_ThreadSupport_Object;
typedef struct ti_sdo_xdcruntime_linux_ThreadSupport_Struct ti_sdo_xdcruntime_linux_ThreadSupport_Struct;
typedef ti_sdo_xdcruntime_linux_ThreadSupport_Object* ti_sdo_xdcruntime_linux_ThreadSupport_Handle;
typedef struct ti_sdo_xdcruntime_linux_ThreadSupport_Object__ ti_sdo_xdcruntime_linux_ThreadSupport_Instance_State;
typedef ti_sdo_xdcruntime_linux_ThreadSupport_Object* ti_sdo_xdcruntime_linux_ThreadSupport_Instance;

/*
 * ======== module ti.sdo.xdcruntime.linux.TimestampPosix ========
 */

typedef struct ti_sdo_xdcruntime_linux_TimestampPosix_Fxns__ ti_sdo_xdcruntime_linux_TimestampPosix_Fxns__;
typedef const ti_sdo_xdcruntime_linux_TimestampPosix_Fxns__* ti_sdo_xdcruntime_linux_TimestampPosix_Module;


#endif /* ti_sdo_xdcruntime_linux__ */ 
